query: segment_g
dset_name: qvhighlight_gen_segment

# multi-modal query
multi_query: false
query_type: segment # text, segment, segment_text
t_feat_dir: {"text":'data/QVHighlight/features/clip_text', "segment":['data/QVHighlight/features/clip_segment_g']} #新加
