query: image_c_text_c
dset_name: qvhighlight_gen_segment

# multi-modal query
multi_query: true
query_type: segment_text # text, segment, segment_text # 要改
t_feat_dir: {"text":'data/QVHighlight/features/clip_text_c', "segment":['data/QVHighlight/features/clip_image_c']} # 要改
