query: segment_text
dset_name: qvhighlight_segment

# multi-modal query
multi_query: true
query_type: segment_text # text, segment, segment_text
t_feat_dir: {"text":'data/QVHighlight/features/clip_text', "segment":['data/QVHighlight/features/clip_video', 'data/QVHighlight/features/slowfast_video']} #新加